package com.gi.login;

import com.gi.home.CustomerHomeFrame;
import com.gi.home.DrivingSchoolHomeFrame;
import com.gi.signup.SignupFrame;
import com.gi.utilities.UIUtility;
import drivingschool.DrivingSchooolFrame;
import AuthorityLogin.*;
import AuthorityLogin.AuthorityModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
        UIUtility.setPlaceHolder(umobile, "Enter The Mobile");
        UIUtility.setPlaceHolder(upassword, "Enter The Password");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        umobile = new javax.swing.JTextField();
        upassword = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        singupBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 322;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 208, 0, 190);
        jPanel1.add(jLabel1, gridBagConstraints);
        jLabel1.getAccessibleContext().setAccessibleDescription("loginlbl");

        umobile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        umobile.setForeground(new java.awt.Color(153, 0, 0));
        umobile.setText("Enter The Mobile No.");
        umobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        umobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umobileActionPerformed(evt);
            }
        });

        upassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        upassword.setForeground(new java.awt.Color(153, 0, 0));
        upassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        loginBtn.setBackground(new java.awt.Color(153, 0, 0));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        singupBtn.setBackground(new java.awt.Color(153, 0, 0));
        singupBtn.setForeground(new java.awt.Color(255, 255, 255));
        singupBtn.setText("Sign Up");
        singupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singupBtnActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(153, 0, 0));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Driving School", "Govt. Authority" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(upassword, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(umobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(umobile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(upassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(singupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        upassword.getAccessibleContext().setAccessibleName("Enter The Password");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 208, 28, 190);
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 48, 6, 79);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umobileActionPerformed

    private void singupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singupBtnActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 0) {
            SignupFrame hf = new SignupFrame();
            hf.setVisible(true);
            this.setVisible(false);
        } else {
            drivingschool.DrivingSchooolFrame hf = new DrivingSchooolFrame();
            hf.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_singupBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        int id = 0;
        String mob = umobile.getText();
        String upass = upassword.getText();
        if (mob.isEmpty()) {
            umobile.requestFocus();
            JOptionPane.showMessageDialog(null, "Please Fill Up the Mobile");
        } else if (upass.isEmpty()) {
            upassword.requestFocus();
            JOptionPane.showMessageDialog(null, "Please Fill Up the Password");
        } else {

            try {
                int index = jComboBox1.getSelectedIndex();
                if (index == 0) {
                    LoginDao ld = new LoginDao();
                    LoginModel sm = new LoginModel(mob, upass);

                    boolean status = ld.fetchcustomer(sm);
                    if (status == true) {
                        System.out.println("Found");
                        CustomerHomeFrame chf = new CustomerHomeFrame();
                        chf.setVisible(true);
                        this.setVisible(false);
                        //JOptionPane.showMessageDialog(this, "Sucessfully Login");
                    } else {
                        JOptionPane.showMessageDialog(this, "Unsucessfully Login");
                    }
                } else if(index == 1) {
                    LoginDao ld = new LoginDao();
                    LoginModel sm = new LoginModel(mob, upass);

                    boolean status = ld.fetchDrivingSchool(sm);
                    if (status == true) {
                        //System.out.println("FoundCustomerHomeFrame  CustomerHomeFrame    HomeFrame hf = new HomeFrame();
                        DrivingSchoolHomeFrame dshf = new DrivingSchoolHomeFrame();

                        dshf.setVisible(true);
                        this.setVisible(false);
                        //JOptionPane.showMessageDialog(this, "Suucessfully Login");
                    } else {
                        JOptionPane.showMessageDialog(this, "Login Is Unsuccessfully");
                    }
                }
                else {
                    /*AuthorityDao ld = new AuthorityDao();
                    AuthorityModel sm = new AuthorityModel(mob, upass);*/
                    LoginDao ld = new LoginDao();
                    LoginModel sm = new LoginModel(mob, upass);

                    boolean status = ld.fetchAuthority(sm);
                    if (status == true) {
                        //System.out.println("FoundCustomerHomeFrame  CustomerHomeFrame    HomeFrame hf = new HomeFrame();
                        AuthorityHomeFrame af = new AuthorityHomeFrame();

                        af.setVisible(true);
                        this.setVisible(false);
                        //JOptionPane.showMessageDialog(this, "Suucessfully Login");
                    } else {
                        JOptionPane.showMessageDialog(this, "Login Is Unsuccessfully");
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton singupBtn;
    private javax.swing.JTextField umobile;
    private javax.swing.JPasswordField upassword;
    // End of variables declaration//GEN-END:variables

}
