package com.gi.login;



import com.gi.signup.SignupFrame;
import com.gi.utilities.UIUtility;
import drivingschool.DrivingSchooolFrame;
import AuthorityLogin.*;
import ColorClass.AppColor;
import CustomerHome.CustomerHomeFrame1;
import DrivingSchoolHome.DrivingSchoolFrame;
import com.AdminHome.AdminLoginHome;
import com.gi.login.AdminLogin.AdminLoginDao;
import com.gi.login.AdminLogin.AdminLoginModel;

import com.gi.login.AuthorityLogin.AuthorityLoginDao;
import com.gi.login.AuthorityLogin.AuthorityLoginModel;
import com.gi.login.CustomerLogin.CustomerLoginDao;
import com.gi.login.CustomerLogin.CustomerLoginModel;
import com.gi.login.DrivingSchoolLogin.DrivingSchoolLoginDao;
import com.gi.login.DrivingSchoolLogin.DrivingSchoolLoginModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LoginFrame extends javax.swing.JFrame {

    public LoginFrame() {
        initComponents();
        
        UIUtility.setPlaceHolder(umobile, "Enter The Mobile");
        UIUtility.setPlaceHolder(upassword, "Enter The Password");
        setResizable(false);
        
        
        umobile.addKeyListener(new KeyAdapter() {
         public void keyPressed(KeyEvent ke) {
            String value = umobile.getText();
            int l = value.length();
            if (ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9') {
               umobile.setEditable(true);
            } else {
               umobile.setEditable(false);
               JOptionPane.showMessageDialog(LoginFrame.this, "* Enter only numeric digits(0-9)");
            }
         }
      });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        umobile = new javax.swing.JTextField();
        upassword = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        singupBtn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 322;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(79, 238, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);
        jLabel1.getAccessibleContext().setAccessibleDescription("loginlbl");

        umobile.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        umobile.setForeground(new java.awt.Color(153, 0, 0));
        umobile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        umobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umobileActionPerformed(evt);
            }
        });
        umobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                umobileKeyPressed(evt);
            }
        });

        upassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        upassword.setForeground(new java.awt.Color(153, 0, 0));
        upassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        loginBtn.setBackground(new java.awt.Color(153, 0, 0));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        singupBtn.setBackground(new java.awt.Color(153, 0, 0));
        singupBtn.setText("Sign Up");
        singupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singupBtnActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(149, 117, 205));
        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Driving School", "Govt. Authority", "Admin" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Mobile No:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Password:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(upassword)
                        .addComponent(umobile, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(singupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umobile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        upassword.getAccessibleContext().setAccessibleName("Enter The Password");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 238, 6, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 48, 41, 299);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umobileActionPerformed

    private void singupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singupBtnActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getSelectedIndex() == 0) {
            SignupFrame hf = new SignupFrame();
            hf.setVisible(true);
            hf.setExtendedState(JFrame.MAXIMIZED_BOTH);
            hf.setUndecorated(true);
            this.setVisible(false);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            drivingschool.DrivingSchooolFrame hf = new DrivingSchooolFrame();
            hf.setVisible(true);
            hf.setExtendedState(JFrame.MAXIMIZED_BOTH);
//            hf.setUndecorated(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Can not signup Authority!!!");
        }
    }//GEN-LAST:event_singupBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        int id = 0;
       String mob = umobile.getText();
        String upass = upassword.getText();

        if (mob.isEmpty()) {
            umobile.requestFocus();
            JOptionPane.showMessageDialog(null, "Please Fill Up the Mobile");
        } else if (mob.length() != 10) {
            umobile.requestFocus();
            JOptionPane.showMessageDialog(null, "Please Enter Valid Mobile Number ");
        } else if (upass.isEmpty()) {
            upassword.requestFocus();
            JOptionPane.showMessageDialog(null, "Please Fill Up the Password");
        } else {

            try {
                int index = jComboBox1.getSelectedIndex();
                if (index == 0) {
                    CustomerLoginDao ld = new CustomerLoginDao();
                    CustomerLoginModel sm = new CustomerLoginModel(mob, upass);

                    CustomerLoginModel cid = ld.fetchcustomer(sm);
                    if (cid != null) {
                        this.setVisible(false);
                        
                        com.customer.CustomerHomeFrame customerHome;
                        customerHome = new com.customer.CustomerHomeFrame(cid.getCid(),cid.getCname());
                        customerHome.setVisible(true);
//                       CustomerHomeFrame1 chf = new CustomerHomeFrame1(cid.getCid(),cid.getCname());
//                        chf.setVisible(true);
                        customerHome.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        chf.setUndecorated(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Credential");
                    }
                } else if (index == 1) {
                    
                    DrivingSchoolLoginDao ld = new DrivingSchoolLoginDao();
                    DrivingSchoolLoginModel sm = new DrivingSchoolLoginModel(mob, upass);

                    DrivingSchoolLoginModel did = ld.fetchDrivingSchool(sm);
                    if (did != null) {
                        this.setVisible(false);
                          com.drivingschool.DrivingSchoolHomeFrame drivingSchoolHome;
                        drivingSchoolHome = new com.drivingschool.DrivingSchoolHomeFrame(did.getDid(),did.getDname());
                        drivingSchoolHome.setVisible(true);
//                        DrivingSchoolFrame dshf = new DrivingSchoolFrame(did.getDid(),did.getDname());

//                        dshf.setVisible(true);
                        drivingSchoolHome.setVisible(true);
                        drivingSchoolHome.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        dshf.setUndecorated(true);
                        //JOptionPane.showMessageDialog(this, "Sucessfully Login");
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Credential");
                    }
                    
                } else if(index == 2)
                {
                    
                    AuthorityLoginDao ld = new AuthorityLoginDao();
                    AuthorityLoginModel sm = new AuthorityLoginModel(mob, upass);

                    AuthorityLoginModel aid = ld.fetchAuthority(sm);
                    if (aid != null) {
                        this.setVisible(false);
                        AuthorityHomeFrame af = new AuthorityHomeFrame(aid.getAid(),aid.getAname());

                        af.setVisible(true);
                        af.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        af.setUndecorated(true);   
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Credential");
                    }
                }
                else
                {
                    AdminLoginDao ld = new AdminLoginDao();
                    AdminLoginModel sm = new AdminLoginModel(mob, upass);

                    AdminLoginModel adid = ld.fetchAdmin(sm);
                    if (adid != null) {
                        this.setVisible(false);
                        AdminLoginHome adl = new AdminLoginHome(adid.getAdid(),adid.getAdname());
                        adl.setVisible(true);
                        adl.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                        adl.setUndecorated(true);
                        
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Credential");
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void umobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_umobileKeyPressed
          
    }//GEN-LAST:event_umobileKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton singupBtn;
    private javax.swing.JTextField umobile;
    private javax.swing.JPasswordField upassword;
    // End of variables declaration//GEN-END:variables

}
