/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DrivingSchoolHome;

import CustomerHome.*;
import AuthorityLogin.DrivingSchoolModel;
import AuthorityLogin.TypeVehicleModel;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sundermetpalli
 */
public class DrivingSchoolFrame extends javax.swing.JFrame {

    List<StatusModel> tv = null;
    List<ApplyModel> tv1 = null;
    List<TestModel> tv2 = null;
    List<VehicleModel> tv3 = null;
    List<OffDaysModel> tv4 = null;
    List<ApplicantModel> tv5 = null;

    /**
     * Creates new form CustomerHomeFrame
     */
    public DrivingSchoolFrame() {
        initComponents();
        //Vehicle2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        vehicleBtn = new javax.swing.JButton();
        applicantBtn = new javax.swing.JButton();
        offdayBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Vehicle2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        dsvehicleTable = new javax.swing.JTable();
        ApplicantPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        applicantTable = new javax.swing.JTable();
        offdayPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        offdaysTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Driving School");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        vehicleBtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        vehicleBtn.setForeground(new java.awt.Color(153, 0, 0));
        vehicleBtn.setText("Vehicle");
        vehicleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBtnActionPerformed(evt);
            }
        });

        applicantBtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        applicantBtn.setForeground(new java.awt.Color(153, 0, 0));
        applicantBtn.setText("Applicants");
        applicantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantBtnActionPerformed(evt);
            }
        });

        offdayBtn.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        offdayBtn.setForeground(new java.awt.Color(153, 0, 0));
        offdayBtn.setText("Off Days");
        offdayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offdayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleBtn)
                .addGap(18, 18, 18)
                .addComponent(applicantBtn)
                .addGap(18, 18, 18)
                .addComponent(offdayBtn)
                .addContainerGap(566, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleBtn)
                    .addComponent(applicantBtn)
                    .addComponent(offdayBtn))
                .addGap(14, 14, 14))
        );

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(153, 0, 0));
        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("+   Add New Vehicle ");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        dsvehicleTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dsvehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Fees", "Delete"
            }
        ));
        jScrollPane8.setViewportView(dsvehicleTable);

        javax.swing.GroupLayout Vehicle2Layout = new javax.swing.GroupLayout(Vehicle2);
        Vehicle2.setLayout(Vehicle2Layout);
        Vehicle2Layout.setHorizontalGroup(
            Vehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vehicle2Layout.createSequentialGroup()
                .addContainerGap(659, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane8)
        );
        Vehicle2Layout.setVerticalGroup(
            Vehicle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vehicle2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );

        jPanel4.add(Vehicle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        applicantTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Customer Name", "Mobile", "Vehicle", "Apply Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(applicantTable);

        javax.swing.GroupLayout ApplicantPanelLayout = new javax.swing.GroupLayout(ApplicantPanel);
        ApplicantPanel.setLayout(ApplicantPanelLayout);
        ApplicantPanelLayout.setHorizontalGroup(
            ApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
            .addGroup(ApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE))
        );
        ApplicantPanelLayout.setVerticalGroup(
            ApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(ApplicantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        jPanel4.add(ApplicantPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 6, -1, -1));

        offdaysTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(offdaysTable);

        javax.swing.GroupLayout offdayPanelLayout = new javax.swing.GroupLayout(offdayPanel);
        offdayPanel.setLayout(offdayPanelLayout);
        offdayPanelLayout.setHorizontalGroup(
            offdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
            .addGroup(offdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(offdayPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );
        offdayPanelLayout.setVerticalGroup(
            offdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
            .addGroup(offdayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(offdayPanelLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGap(15, 15, 15)))
        );

        jPanel4.add(offdayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applicantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantBtnActionPerformed
        // TODO add your handling code here:
        Vehicle2.setVisible(false);
        ApplicantPanel.setVisible(true);
        offdayPanel.setVisible(false);
        try {
            populateTable1();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_applicantBtnActionPerformed

    private void populateTable1() throws Exception {
        //get driving school id from driving school login page
        //pass that id to apply_driving_school and get cid,vech_id,apply_date,status
        //find customer details using cid
        //find vechicle name using vech_id
        // and load on table
        ApplicantDao dBOperations1 = new ApplicantDao();

        DefaultTableModel model = (DefaultTableModel) applicantTable.getModel();
        model.setRowCount(0);
        tv5 = dBOperations1.fetchApplicant();
        for (ApplicantModel person1 : tv5) {

            System.out.println(person1);
            Object[] row = new Object[11];
            row[0] = person1.getId();
            row[1] = person1.getCustomer_name();
            row[2] = person1.getCustomer_contact();
            row[3] = person1.getVehicle();
            row[4] = person1.getApply_date();
            row[5] = person1.getStatus();
            //row[8] = "Enable";

            /*if (person1.getStatus() == "true") {
                row[5] = "Active";
            } else {
                row[5] = "Deactive";
            }*/
            model.addRow(row);
        }
    }

    private void vehicleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBtnActionPerformed
        // TODO add your handling code here:
        Vehicle2.setVisible(true);
        ApplicantPanel.setVisible(false);
        offdayPanel.setVisible(false);

        try {
            populateTable3();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_vehicleBtnActionPerformed

    private void populateTable3() throws Exception {
        VehicleDao dBOperations1 = new VehicleDao();

        DefaultTableModel model = (DefaultTableModel) dsvehicleTable.getModel();
        model.setRowCount(0);
        tv3 = dBOperations1.fetchVehicle();
        for (VehicleModel person1 : tv3) {

            System.out.println(person1);
            Object[] row = new Object[11];
            row[0] = person1.getId();
            row[1] = person1.getName();
            row[2] = person1.getFees();
            row[8] = "DELETE";

            /*if (person1.getStatus() == "true") {
                row[5] = "Active";
            } else {
                row[5] = "Deactive";
            }*/
            model.addRow(row);
        }
    }
    private void offdayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offdayBtnActionPerformed
        // TODO add your handling code here:
        Vehicle2.setVisible(false);
        ApplicantPanel.setVisible(false);
        offdayPanel.setVisible(true);

        try {
            populateTable2();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_offdayBtnActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        //AddNewVehicleFrame1 anv = new AddNewVehicleFrame1();
        //anv.setVisible(true);

        //TypeVehicleModel tpv = new TypeVehicleModel();
        //String name = name.get
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void populateTable2() throws Exception {
        OffDaysDao dBOperations2 = new OffDaysDao();

        DefaultTableModel model1 = (DefaultTableModel) offdaysTable.getModel();
        model1.setRowCount(0);
        tv4 = dBOperations2.fetchOffDays();
        for (OffDaysModel person1 : tv4) {

            System.out.println(person1);
            Object[] row = new Object[11];
            row[0] = person1.getId();
            row[1] = person1.getDate();
            model1.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrivingSchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrivingSchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrivingSchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrivingSchoolFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrivingSchoolFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApplicantPanel;
    private javax.swing.JPanel Vehicle2;
    private javax.swing.JButton applicantBtn;
    private javax.swing.JTable applicantTable;
    private javax.swing.JTable dsvehicleTable;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton offdayBtn;
    private javax.swing.JPanel offdayPanel;
    private javax.swing.JTable offdaysTable;
    private javax.swing.JButton vehicleBtn;
    // End of variables declaration//GEN-END:variables
}
